package fpmbuild.superinject;

import fpmbuild.json.Json;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

final class SuperInjectionMetadata {
    private SuperInjectionMetadata() {}

    static byte[] fabric(ModuleMetadata module, String version) {
        Map<String,Object> json = new LinkedHashMap<>();
        json.put("schemaVersion", 1);
        json.put("id", module.injectedModId());
        json.put("version", version == null || version.isBlank() ? "12" : version);
        json.put("mixins", module.mixinConfigs());
        return utf8(Json.stringify(json) + "\n");
    }

    static byte[] neoForge(ModuleMetadata module, String version) {
        StringBuilder b = new StringBuilder();
        b.append("modLoader=\"javafml\"\n");
        b.append("loaderVersion=\"[0,)\"\n");
        b.append("license=\"All Rights Reserved\"\n\n");
        b.append("[[mods]]\n");
        b.append("modId=\"").append(toml(module.injectedModId())).append("\"\n");
        b.append("version=\"").append(toml(defaultVersion(version))).append("\"\n");
        b.append("description=\"FeatureCreep superinjection bridge\"\n");
        for (String mixin : module.mixinConfigs()) {
            b.append("\n[[mixins]]\nconfig=\"").append(toml(mixin)).append("\"\n");
        }
        return utf8(b.toString());
    }

    static byte[] forge(ModuleMetadata module, String version) {
        StringBuilder b = new StringBuilder();
        b.append("modLoader=\"javafml\"\n");
        b.append("loaderVersion=\"[0,)\"\n");
        b.append("license=\"All Rights Reserved\"\n\n");
        b.append("[[mods]]\n");
        b.append("modId=\"").append(toml(module.injectedModId())).append("\"\n");
        b.append("version=\"").append(toml(defaultVersion(version))).append("\"\n");
        b.append("displayName=\"").append(toml(module.injectedModId())).append("\"\n");
        b.append("description=\"FeatureCreep superinjection bridge\"\n");
        return utf8(b.toString());
    }

    static byte[] sponge(ModuleMetadata module, String version, String entrypoint) {
        Map<String,Object> loader = Json.object("name","java_plain","version","1.0");
        Map<String,Object> contributor = Json.object("name","FeatureCreep","description","Generated by FPMBuild superinjection");
        Map<String,Object> global = Json.object("version", defaultVersion(version), "contributors", List.of(contributor));
        Map<String,Object> plugin = Json.object("id", module.injectedModId(), "entrypoint", entrypoint);
        return utf8(Json.stringify(Json.object(
                "loader", loader,
                "license", "All Rights Reserved",
                "global", global,
                "plugins", List.of(plugin))) + "\n");
    }

    static String mixinManifestValue(ModuleMetadata module) {
        return String.join(",", module.mixinConfigs());
    }

    private static String defaultVersion(String version) { return version == null || version.isBlank() ? "12" : version; }
    private static String toml(String value) { return value.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r"); }
    private static byte[] utf8(String value) { return value.getBytes(java.nio.charset.StandardCharsets.UTF_8); }
}
